### ISSUE TITLE
[BUG] IOS和Android客户端发送语音样式与web端不统一

### ISSUE THREAD

**Issue by Kings-Github** [Privoce/vocechat-client#133]
环境：

- 服务器端版本: 0.3.7
- IOS客户端版本：0.2.91
- Android客户端版本：0.2.92

问题描述：

Web端接收到的语音文件拥有波形图、可以随意在音频文件上点击来控制语音播放位置，但是IOS和Android客户端无法实现这一点。
希望后续改进此功能。

**Comment by shuotwang** [comment]
移动端可以拖动语音消息的播放进度条调整。波形图暂无计划，或许在后期核心功能稳定之后优化。

**Comment by shuotwang** [comment]
如无更多问题，此issue暂时关闭。
