### ISSUE TITLE
配置firebase后无法收到推送

### ISSUE THREAD

**Issue by sniper54** [Privoce/vocechat-client#22]
配置后无法收到推送，只能在界面中显示 

版本：IOS/Android

**Comment by shuotwang** [comment]
后端目前在针对 Firebase 的问题做改动，一到两周之内会有更新，但体验仍然会不够理想。 app 必须经由具体项目签名。换言之，因为 app 目前是由我们签名上传，即使用户自定义配置了推送服务，签名也无法匹配，导致自配置推送无法实现 app 的推送。目前计划是留有默认推送配置，或是自定义配置，但自定义配置会导致 app 推送不可用。这是目前多数推送中心化的特性导致。

**Comment by stilleshan** [comment]
@shuotwang 虽然我不太懂关于 iOS 推送,但是有个其他项目 bark 推送貌似就是用的 APNs 推送,体验也很好,不知道是否能实现?

**Comment by shuotwang** [comment]
@stilleshan 即将上线的改动会和 bark 类似，我们会提供一套默认的配置。bark 我初步判断也是类似，可以从不同自部署服务端发到到一个固定的APNS项目，但从该APNS到手机只能走一条路，即指定的APNS以及客户端。目前自配置推送的问题是，在APNS创建了新项目，但手机的项目又是固定不变的，导致APNS（firebase类似）和客户端的绑定关系错误。

**Comment by stilleshan** [comment]
@shuotwang 不知道我描述是否正确, bark 作者提供了 iOS 客户端, 我们虽然是自己部署服务, 用的他的客户端就可以用推送,听说貌似有推送次数限制吧.

**Comment by shuotwang** [comment]
@stilleshan 哦明白你的意思了。实现这个目前分析技术上没有难度，我们团队要讨论一下，同时也会收集多一点反馈再计划是否实现它。但我个人观点是没有大必要，用 vocechat app 也能以类似形式收推送，服务端也是自部署的，消息会直接发到推送服务器上。

**Comment by shuotwang** [comment]
初步更新已经上线，请参考 doc 中更新的说明：https://doc.voce.chat/zh-cn/setting/setting-firebase-notification。后期会有更针对国内推送环境的更新。
