### ISSUE TITLE
手机端建议新增中文选项

### ISSUE THREAD

**Issue by mucstudio** [Privoce/vocechat-client#27]
如果是国内用户比较多的话，或者有意向发展国内客户的，建议增加一个中文的语言，毕竟英文对国人来说很多时候还是不太方便的。

**Comment by zephyr-y** [comment]
期待中文选项

**Comment by shuotwang** [comment]
目前先修复更影响使用的bug，中文的排期会稍后，有空也会穿插进行。

**Comment by shuotwang** [comment]
中文版已经完成，新版本经测试后尽快交审核。
