### ISSUE TITLE
BUG: ios app中，使用自带输入法打字，输入框的光标不对。

### ISSUE THREAD

**Issue by WSure00** [Privoce/vocechat-client#46]
BUG: ios app中，使用自带输入法打字，输入框的光标不对。

**Comment by WSure00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WSure00** [comment]
https://user-images.githubusercontent.com/39566033/206830572-49794e17-c0b7-4bea-8536-d60e48f7bb2c.MOV

**Comment by shuotwang** [comment]
这有点奇怪，我这暂时复现不了。我们先看看

**Comment by shuotwang** [comment]
找到了复现的情景了，即在私聊中出现，群聊没有这个问题。初步判定和 at 人的功能相关，正在修复中。

**Comment by shuotwang** [comment]
已修复，新版本 0.2.59 在审核中。
