### ISSUE TITLE
bug: app 不同服务器切换登录导致数据混乱 | Switching logins between different servers leads to data clutter

### ISSUE THREAD

**Issue by kkbt0** [Privoce/vocechat-client#49]
触发方式 同时登录官网实例和自建实例   
由于官网同步数据很慢，切换到自建实例很快。会将官网数据刷新到自建实例列表里。  

甚至app中自建实例用户列表中会显示一部分官网实例用户。在app自建实例用户中的官网对话中，会有官网实例用户是自建实例中的名字，头像。就像被盗号了似的。 

---

Trigger method: Log in to the official instance and the self-hosted instance at the same time.
Due to the slow synchronization of data on the official , switching to a self-hosted instance before data refresh is quickly obtained. The official instance data will be refreshed to the list of self-hosted instance.

Even a part of  official instance users list will be displayed in self-hosted instance users  list in the app. 

 In self-hosted instance discuss lists (the data came from official instance ), there will be official instance users who have same name , mail and avatar with my account. It's like being hacked.

**Comment by shuotwang** [comment]
问题已解决，会更新在版本0.2.60，正在审核中。
