### ISSUE TITLE
下载下代码，提示缺少文件。请上传一下。GoogleService-Info.plist'

### ISSUE THREAD

**Issue by csc-EricWu** [Privoce/vocechat-client#56]
Showing All Errors Only
Build input file cannot be found: '/Users/make/github/vocechat-client/ios/Runner/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

**Comment by shuotwang** [comment]
此文件用于 Firebase 的配置，其中包含仅 Privoce 团队可见的信息，请使用自己的 Firebase 配置文件。
