### ISSUE TITLE
[BUG]安卓两个bug

### ISSUE THREAD

**Issue by superen7527** [Privoce/vocechat-client#88]
~app：不说推送，新发的信息也转圈圈转不出来。发消息不支持回车换行~

网页：没适配手机ua 聊天界面不友好

**Comment by shuotwang** [comment]
请问“新发的信息也转圈圈转不出来” 是指发送之后，消息右侧的圈一直转么？是什么类型的消息，文字、图片还是回复等等？是否出现了重试按钮（红色叹号）？能说明一下手机型号、安卓系统版本和app版本号吗？

**Comment by shuotwang** [comment]
换行问题：测试了原生安卓API 31 on google pixel 5，可以正常换行。

**Comment by superen7527** [comment]
不好意思，我仔细看了一下，发现你们官网提供的安装包，和gp上安装包版本不一样。

我最开始用的官网的安装包，你回复后我对比了两个版本号，谷歌比较新。可能是我用的旧版才有的问题。

但是谷歌上0.2.70版本我打不开，打开就闪退，无法继续测试。

安卓11，MIUI系统。可能问题已经在新版上修复了，我关闭issue吧。

**Comment by superen7527** [comment]
忘了还有个网页适配安卓ua的反馈，我重新开一下。
